apiVersion: apps/v1
kind: Deployment
metadata:
  name: 66-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 66-app
  template:
    metadata:
      labels:
        app: 66-app
    spec:
      containers:
      - name: 66-container
        image: ashhyeong/66:latest
        env:
          - name: TZ
            value: "Asia/Seoul"
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
          requests:
            memory: "64Mi"
            cpu: "100m"